### ISSUE TITLE
ENTK all task outputs

### ISSUE THREAD

**Issue by ValHayot** [radical-collaboration/Glatard-Lab#3]
Hi,

Sorry if I missed it, but I'm unsure of where to look to find all task outputs. I've been looking in `pilot.0000/None/STD(OUT/ERR)`, but it seems to only have the output of only the last task that was executed by radical pilot. Is this expected? Is there a way to get the outputs from all the tasks?

Thanks!!

**Comment by ValHayot** [comment]
I looked more closely at the task api and noticed we can specify stdout/stderr. I suppose if i want the std out/err for all my tasks i just need to pass unique log name as a parameter of the task, otherwise they risk being overwritten?

**Comment by andre-merzky** [comment]
Hi @ValHayot : the `None` element in the path was a bug.  The correct case is that each task has it's own sandbox, and that each task's output is separate in those sandboxes.  The last release of the RCT stack should have this problem  fixed, and we'd thus like  to ask you to update your stack and run again.  Let us know  how it goes!

**Comment by ValHayot** [comment]
Works great! Thanks!
