### ISSUE TITLE
ENTK: is there a way to specify task environment?

### ISSUE THREAD

**Issue by ValHayot** [radical-collaboration/Glatard-Lab#4]
Right now I'm setting my executable as `/bin/bash` and passing a bash script that activates my conda environment and executes my task as argument. I was wondering if there was a recommended way to specify the pipeline/task environment in ENTK.

**Comment by andre-merzky** [comment]
You may want to look at the `pre_exec` documentation at https://radicalentk.readthedocs.io/en/latest/api/app_create/task.html.  Basically, you can set pre_exec to:
```python
td.pre_exec = ['export FOO=BAR',
               'conda activate buz']
```
Is that what you are looking for?

**Comment by ValHayot** [comment]
Yep, thanks! I thought I looked through the doc, but clearly not carefully enough!
